typography_spectrum: 0.8729240274988115
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7817727567162365
  lightness: 0.5046494782436639
  saturation: 0.48043549293652177
  rhythmicContrast: 0.9097011310514063
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3789125375915319
analytics:
  google: null
  facebook: null
  twitter: null
name: JONKU
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: FILMMAKER
purpose: []
